// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: upgrade_chirpy.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeChirpy = `-- name: UpgradeChirpy :exec
UPDATE users SET is_chirpy_red = true WHERE id = $1
`

func (q *Queries) UpgradeChirpy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeChirpy, id)
	return err
}
